# Generated by Django 5.0.1 on 2024-01-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=55)),
                ('userSurname', models.CharField(max_length=55)),
                ('userPhone', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=150)),
                ('userAddress', models.TextField()),
                ('iconName', models.CharField(max_length=50)),
            ],
        ),
    ]
